-- ═══ CORRECTION (2026-09-20t, R18) ═══
-- Neeche 'DIAGNOSTIC (owner-action)' wala IMGBB_KEY finding GALAT nikla:
-- Mgmt-API secrets-GET SHA-256(value) return karta hai, asli value NAHI
-- (roundtrip-probe se proven). IMGBB_KEY secret bilkul sahi hai —
-- realistic-image edge-fn upload 200-SUCCESS (i.ibb.co live URL mila).
-- Upload working tha/ hai. Niche wala section historical-galat samjho;
-- sahi lesson DEVELOPER_GUIDE me hai.
-- ═══════════════════════════════════════════════════════════════════
-- 2026-09-20s ROUND-17 — ULTIMATE DEEP-SWEEP (minor features + attacks)
-- ═══════════════════════════════════════════════════════════════════
-- FIXED (live-verified):
--   R17-1 ★ cast_poll_vote: INVALID OPTIONS accept ho rahe the — koi bhi
--     arbitrary option-key ('hack') vote_counts me ban raha tha (results
--     tamper + unbounded keys). FIX: options ? p_option check →
--     invalid_option reject. Verify: hack-blocked / valid-ok / counts-sahi ✓
--   R17-2 ★ BAN-ENFORCEMENT missing: is_banned ka koi server-check hi nahi
--     tha — banned user match join kar sakta tha (fee bhi kharch). FIX:
--     validate_and_join_match me ACCOUNT_BANNED guard (self-play block ke
--     baad). Verify: banned→blocked / unban→join-ok ✓
--   R17-3 gift_match_entry v4: friend AUTO-JOIN restore (purane flow jaisa)
--     — ticket + notif + jr(pending, fee=0) + filled_slots+1. Guards:
--     upcoming-match, not-already-joined, slot-available. Verify: jr+slot ✓
--
-- AUDITED-CLEAN (is round):
--   claim_creator_payout (FOR UPDATE + zeroing; admin pays offline — design ✓)
--   claim_match_commission_payout (status-flip only; admin pays — design ✓)
--   users INSERT for arbitrary-uid → 401 blocked ✓
--   support_messages outsider-inject → blocked ✓
--   OneSignal: CDN-SDK worker only, koi API-key embedded nahi ✓
--   User-panel UI breadth: 18/18 screens 0-console-errors ✓
--
-- DIAGNOSTIC (owner-action):
--   ★ IMGBB_KEY secret me 64-char hex (SHA-256 HASH) pada hai — ImgBB key
--     32-char hex hoti hai. Isi liye uploads 'forbidden' de rahe hain.
--     FIX: api.imgbb.com se ASLI key copy karke
--     `supabase secrets set IMGBB_KEY=<32-char-key>` — code path 100% OK hai.
--   PayTM: admin-toggle OFF = manual payments (by-design) — jab PAYTM_*
--     secrets + toggle ON hoga tab auto-flow live (code ready+tested).
-- ═══════════════════════════════════════════════════════════════════
