-- ═══════════════════════════════════════════════════════════════
-- ROUND-23 DELTA (2026-09-21) — APK NATIVE PUSH + OCR v2.2b
-- ═══════════════════════════════════════════════════════════════
-- कोई नया schema object नहीं। Push-chain (ext pg_net, push_hook_config,
-- notifications_push_hook(), trg_notifications_push) पहले ही live है।
--
-- इस round के बदलाव code/config-स्तर के:
--   1. user-repo android: MyApplication appId f263d25f(dead) -> a65c45fc
--      + OneSignal.login/logout WebView-bridge + POST_NOTIFICATIONS (API33+)
--      + versionCode 4 / versionName 1.0.3  [commits 5457156, 553cdbd, 82510d8]
--   2. admin-repo: OCR v2.2b (commits bea88b6, a94ba44, cache-tag 20260921c)
--
-- PENDING USER-OPS (कुछ भी SQL में नहीं — dashboard-ops):
--   • OneSignal wizard: Native Android + FCM service-account JSON (fft-app-1e283)
--   • नए app a65c45fc की Legacy REST key → तब यह चलाना:
--       select vault_update_secret('ONESIGNAL_REST_KEY', '<नई-कुंजी>');  -- या Mgmt secrets API
--   • उसके बाद send-test (include_aliases external_id = firebase-uid)
-- NOTE: पुराना app 1f867c88 जीवित (पुरानी key से 200/200) — pivot-विकल्प।

-- (2026-09-21 addendum) OCR v2.3 — commit 64813be, cache-tag 20260921d; कोई schema-बदलाव नहीं (सिर्फ admin JS)।
-- (2026-09-21 addendum-2) OCR v2.4 — commit 1722319, cache-tag 20260921e; कोई schema-बदलाव नहीं (सिर्फ admin JS)।
-- (2026-09-21 addendum-3) CRITICAL CSP-FIX: worker-src blob: + wasm-unsafe-eval + tessdata/jsdelivr — real Tesseract worker CSP-blocked था; REAL-E2E 2/2 PASS (c7029eb)। कोई schema-बदलाव नहीं।
-- (2026-09-21 addendum-4) OneSignal AI-prompt integration: SDK 5.1.6->5.9.2 stable, OneSignalManager wrapper, verification-dialog, launch-prompt हटा; APK vc5/1.0.4 success+dex-verified (dd49685)। कोई schema-बदलाव नहीं।
-- (2026-09-21 FINAL) REST-key SWAP पूर्ण + LIVE-chain 200 (raw-Basic v2-key सीख) — कोई schema-बदलाव नहीं।
-- (2026-09-21 R24) dead-code −3200+ लाइनें (creator-video-feed + 139 fns) + Java-protected-set सीख + OneSignal autoRegister-off + perf-माप (2MB cold, CSS-72-dup, admin-boot-15s) — कोई schema-बदलाव नहीं।
