-- ============================================================
-- SESSION DELTA — 2026-09-20
-- SECURITY LOCKDOWN + PUBLISH RLS FIX + SCHEMA RECONCILIATION
-- All SQL below ALREADY APPLIED live (via Supabase Management API)
-- and verified with real REST tests. This file = audit record.
-- COMPLETE_SCHEMA.sql SECTION 23 me merge ho chuka hai.
-- ============================================================
--
-- CONTEXT: 2026-09-19/20 ko poore panel ka deep live security audit
-- hua (qa1/qa2/qa3 test users, REST-level attacks, DB-verified).
-- Findings + fixes:
--
-- ── FINDING 1 (fixed pehle hi, not by this session): users self-edit ──
-- S1-S4 tests (coins=99999, is_admin=true, self-unban, ban_reason tamper)
-- ne 2026-09-19 ko OPEN holes dikhaye the. Is session ke live retest me
-- wo BLOCKED mile — trg_guard_users_self_update + guard_users_self_update()
-- (whitelist-only self-edit) beech me kisi session ne add kar diya tha.
-- ✅ kuch nahi karna pada — bas audit record ke liye note.
-- NOTE: is guard ki wajah se Supabase SQL Editor / Mgmt API se bhi
-- users row update nahi hoti (auth.jwt() NULL → v_caller NULL → raise).
-- DB-level fixes users par chahiye to: SET LOCAL role='service_role';
-- <UPDATE>; RESET role; (ek hi batch me).
--
-- ── FINDING 2 (FIXED this session): wallet_transactions INSERT hole ──
-- Aam user POST /rest/v1/wallet_transactions {txn_type:'match_win',
-- amount:50000} → 201 — apna hi "jeet" bana sakta tha (S5, CRITICAL).
-- FIX: trigger trg_fft_wallet_insert_guard + fft_guard_wallet_insert()
-- (SECURITY INVOKER — definer-RPC context me current_user=postgres
-- hone se RPC writes safe). Verify live:
--   fake match_win → 400 P0001 ✓
--   pending_deposit → 201 ✓ (deposit flow intact)
--   debit/match_entry → 201 ✓ (join flow intact)
--   admin JWT credit → 201 ✓
--
-- ── FINDING 3 (FIXED this session): match_results write hole ──
-- Aam user kisi bhi (ya fake) match ke liye placement-1/prize-9999 row
-- bana sakta tha (S6). FIX: trg_fft_match_results_guard +
-- fft_guard_match_results_write() (INSERT/UPDATE/DELETE, admin/system only).
-- Verify live: user insert → 400 P0001 ✓; admin insert (sahi UUID) → 201 ✓.
--
-- ── FINDING 4 (FIXED this session): publish-flow ka Supabase-half ──
-- Publish par match_results upsert fail hota tha (purane audits me
-- "400 match_results"). Root causes, dono ab fix:
--   a) RLS mr_insert_own sirf own-row INSERT deti thi — admin winner
--      rows kabhi insert nahi kar pata tha → ab mr_insert_admin policy.
--   b) match_id namespace: FK matches.id (UUID) hai. Admin UI se
--      banne wale matches me Firebase key == Supabase UUID hota hai
--      (verified: rtdb key = matches.id), isliye UI-publish flow theek;
--      par koi bhi external/purana Firebase-mid FK-violation (409)
--      dega — error ab console me clearly dikhega (error-log patch
--      admin-inline.js me).
-- Unique constraint match_results_match_id_user_id_key pehle se thi.
--
-- ── CLEANUP (live executed) ──
-- DELETE FROM wallet_transactions WHERE id IN
--   ('292f1193-f8cd-46b6-bf8f-27b32f29385a',   -- S5 fake (audit)
--    '70d79226-f1c2-4e72-981a-d35d698a3dbb');  -- S5 retest fake
-- DELETE FROM match_results WHERE id = '40ef484e-2ca4-4d6d-918a-39078c0a72d3';
-- (teeno audit-fake rows — deleted, verified 0 rows)
--
-- ── SCHEMA RECONCILIATION ──
-- 2026-08-23-SESSION-DELTA.sql ka SQL (premium_monthly_bonus_claims +
-- claim_premium_monthly_bonus + cast_poll_vote + get_my_poll_vote +
-- pmbc policies) live DB me tha par COMPLETE_SCHEMA.sql me missing —
-- ab SECTION 23 (Part A) me merge. Koi aur delta missing nahi tha
-- (10/10 deltas audited, distinctive-object grep se verify).
--
-- ── PANEL CODE CHANGES (same-day push) ──
-- Admin: support-inbox per-uid scanner (root RTDB reads PERMISSION_DENIED
--   the — inbox hamesha khaali), openChat thread render fix (broken
--   Promise.all + wrong sort key), free Entry-Type option + validation,
--   normalizeWalletType polyfill, match_results upsert error-logging.
-- User: Help-menu "Support Chat" button ab navTo('chat') (startChat()
--   screen-switch nahi karti thi — button dead tha).
-- Version bumps: admin-inline/live-dash ?v=20260920a, admin-badge ?v=20260920a.
-- ============================================================

-- ── LATER SAME-DAY (Part C) ──
-- ALTER TABLE match_results ADD "rank"/kill_prize/rank_prize/prize_earned
--   → publish-flow ka ASLI root cause fix (bridge resultToSupa inhe
--     bhejta tha, table me nahi the → 400 → sab players "failed").
-- guard_users_self_update(): DEFINER→INVOKER + current_user check
--   → join-RPC (validate_and_join_match) jo guard ke baad se broken tha
--     ("Column coins is not self-editable") wapas zinda.
-- VERIFY (live): joins ok:true ×2 → publish E2E PASS (2 result rows,
--   prizes 110/55 credit + wallet match_win + match completed) → full revert.
