-- ═══════════════════════════════════════════════════════════════════
-- 2026-09-20t ROUND-18 — MAXIMUM-DEPTH RE-ANALYSIS (post imgbb-correction)
-- ═══════════════════════════════════════════════════════════════════
-- FIXED:
--   R18-1 ★ notifications INSERT-policy v2 (notif_insert): purani policy
--     sirf 'sender real user ho' check karti thi — koi bhi user kisi bhi
--     user ko ADMIN-TYPE fake notification (credit/refund/result/vip...)
--     bhej kar phishing kar sakta tha. NAYA policy:
--     - admin branch: users.is_admin = true → sab types (broadcast OK)
--     - normal-user branch: ALLOWLIST-only (12 client-social types:
--       clan_cosmetic, clan_war_challenge, duel_accepted, duel_challenge,
--       friend_add, gift_ticket, mentor_accepted, mentor_request,
--       mentor_reward, premium, premium_request, squad_request)
--       + char_length(title)<=120 + char_length(body)<=400
--       + banned users send nahi kar sakte
--     - server RPCs (SECURITY DEFINER) RLS bypass — unaffected ✓
--     VERIFY: 12 allowed types 201 ✓ / 12 phish-types 403 ✓ / caps ✓ /
--             own-insert 201 ✓ / admin 'info' 201 ✓ / residue 0 ✓
--     NOTE: naya client notification-type add karte waqt is allowlist me
--     add karna zaroori hai (DEVELOPER_GUIDE R18).
--
-- AUDITED-CLEAN (is round, sab live-verified):
--   increment_balance/decrement_balance: admin-guard + wallet/rank-col
--     lock + stats-cap-100 ('Wallet/rank columns sirf admin/service...')
--   battle_pass_progress: bpp_update_zero → client own-UPDATE 401 ✓
--   award_battle_pass_xp: self-only + 2000 XP/day cap (design-bounded;
--     client match-result se hi call karta hai — battle-pass.js:141)
--   IDOR cross-user matrix (16 tables): INSERT/UPDATE — sirf notifications
--     tha (fix upar); baaki sab 401/403 blocked
--   Dynamic-SQL scan (116 fns): sab EXECUTE format(%I) + USING params —
--     koi injection surface nahi
--   Storage: buckets khali (sab images ImgBB URLs) — surface closed
--   Realtime anon-WS: subscribe OK par 0 row-events (RLS-gated ✓)
--   RTDB: anon GET/PUT sab permission-denied ✓
--   Firebase auth: INVALID_LOGIN_CREDENTIALS generic — no enumeration ✓
--   OpenAPI/pg_meta: anon 401/404 ✓
--   ADMIN_BREADTH re-run: PASS (13 sections + 5 tools, console-errors=1)
-- ═══════════════════════════════════════════════════════════════════
